[package]
name = "communication_layer"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common"}
rdkafka = { version = "0.37.0", features = ["tokio"] }
tokio-stream = "0.1.15"
serde_json = "1.0.132"
tokio = "1.42.0"