[package]
name = "order_management_system"
version = "0.1.0"
edition = "2021"

[dependencies]  
redis = { version= "0.27.5", features = ["tokio-comp"]}
serde_json = "1.0.132"
tokio = { version = "1.41.0", features = ["full"] }
common= { path = "../common" }